export const LOAD_SUBJECTS = "LOAD_SUBJECTS";
export const LOAD_CLASS = "LOAD_CLASS";
export const RESET_CLASS = "RESET_CLASS";

export const ADD_STUDENT = "ADD_STUDENT";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";
export const CREATE_CLASS_START = "CREATE_CLASS_START";
export const CREATE_CLASS_END = "CREATE_CLASS_END";
